version: 2
jobs:
  build:
    docker:
      - image: trieloff/githop:clojurescript
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
        
      # compile
      - run: npm run compile
      
      - save_cache:
          paths:
            - node_modules
            - ~/.m2/repository
          key: v1-dependencies-{{ checksum "package.json" }}

      # build (prod)
      - run: npm run release

      # configure
      - run: npm config set wsk_host $WSK_HOST
      - run: npm config set wsk_key $WSK_KEY

      # package
      - run: npm run package    

      # deploy
      - run: npm run deploy  